version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    steps:
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-26;google_apis;x86"
      - run:
          name: Create emulator
          command: echo no | avdmanager -v create avd -n test -k "system-images;android-26;google_apis;x86"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose
          background: true
      - run:
          name: Wait emulator
          command: |
          # wait for it to have booted
          circle-android wait-for-boot
          # unlock the emulator screen
          sleep 30
          adb shell input keyevent 82
      - run:
          name: Run Tests
          command: ./gradlew connectedAndroidTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results